#!/bin/bash
# Copyright (C) 2014 Alexander Keller <github@nycroth.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#------------------------------------------------------------------------

INTERFACE="${BLOCK_INSTANCE:-wlan0}"

#------------------------------------------------------------------------

# As per #36 -- It is transparent: e.g. if the machine has no battery or wireless
# connection (think desktop), the corresponding block should not be displayed.
[[ ! -d /sys/class/net/${INTERFACE}/wireless ]] ||
    [[ "$(cat /sys/class/net/$INTERFACE/operstate)" = 'down' ]] && exit

#------------------------------------------------------------------------

#QUALITY=$(grep $INTERFACE /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')
QUALITY=$(iw dev wlp9s0 link | grep signal | cut -d " " -f 2-)
SSID=$(iw dev wlp9s0 link | grep SSID | cut -d " " -f 2-)
#------------------------------------------------------------------------

#echo $QUALITY% # full text
#echo $QUALITY% # short text

echo $SSID
echo $SSID
echo "#FFFA69"
# color
#if [[ $QUALITY -ge 0 ]]; then
#    echo "#A1FF4A"
#elif [[ $QUALITY -lt 50 ]]; then
#    echo "#FFF600"
#elif [[ $QUALITY -lt 30 ]]; then
#    echo "#FFAE00"
#elif [[ $QUALITY -lt 10 ]]; then
#    echo "#FF0000"
#fi

